### ISSUE TITLE
How to reproduce the results?

### ISSUE THREAD

**Issue by Smu-Tan** [YuweiYin/HLT-MT#1]
Hi, thanks for uploading the code. Could you please write some examples of how to reproduce some results in the paper? Since markdowns barely exist in the code.

For example, how to reproduce:

1. LS-MNMT that random initialized.
2. HLT-MT without any pre-trained model or SLP.
3. HLT-MT that without any pre-trained model but with SLP.

Furthermore, I found it quite ambiguous for your `HLT-MT Training` example, since you use `two_stage_sparse_transformer`, what does this stands for? HLT-MT with SLP?

Thank you in advance!

**Comment by YuweiYin** [comment]
Thanks for your attention.

The final model, with the SLP module and pre-trained model initialization, is in [this file](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/two_stage_sparse_transformer.py) (`two stage sparse transformer`). The SLP module is required in our method.

* Without SLP, our model will become a vanilla encoder-decoder Transformer structure.
* Without the pre-trained model ([XLM-R](https://aclanthology.org/2020.acl-main.747/)), our model will be randomly initialized by default.
* With the pre-trained model, both the encoder and decoder of our model will be initialized by the pre-trained model.

**Comment by Smu-Tan** [comment]
Thanks for your quick response! 

I intended to reproduce the results without pre-trained models (third row in Table 3). If I understand correctly, I can just ignore `--pretrained-infoxlm-checkpoint`, and set `--init-encoder-only` `--init-decoder-only`?

Furthermore, could you let me know which task you used for LS-MNMT? Perhaps it is language_specific_transformer?

**Comment by YuweiYin** [comment]
> I intended to reproduce the results without pre-trained models (third row in Table 3). If I understand correctly, I can just ignore `--pretrained-infoxlm-checkpoint`, and set `--init-encoder-only` `--init-decoder-only`?

Yes. As Line 571 and Line 577 in [two_stage_sparse_transformer](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/two_stage_sparse_transformer.py) show, the encoder will be initialized with the XLM-R state dict if we pass the `--init-encoder-only` parameter to the training script in README. Similarly, if we pass the `--init-decoder-only` parameter, the decoder will be initialized with the same XLM-R state dict.

Therefore, if you do not want to use the pre-trained models, do not pass `--init-encoder-only` or `--init-decoder-only` to the training script.

As for `--pretrained-infoxlm-checkpoint`, we can ignore this parameter, meaning we do not provide a valid model checkpoint, as mentioned in the [code](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/two_stage_sparse_transformer.py#L727).

> Furthermore, could you let me know which task you used for LS-MNMT? Perhaps it is language_specific_transformer?

**LS-MNMT**: [language_specific_transformer.py](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/language_specific_transformer.py)

**Comment by Smu-Tan** [comment]
> > I intended to reproduce the results without pre-trained models (third row in Table 3). If I understand correctly, I can just ignore `--pretrained-infoxlm-checkpoint`, and set `--init-encoder-only` `--init-decoder-only`?
> 
> Yes. As Line 571 and Line 577 in [two_stage_sparse_transformer](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/two_stage_sparse_transformer.py) show, the encoder will be initialized with the XLM-R state dict if we pass the `--init-encoder-only` parameter to the training script in README. Similarly, if we pass the `--init-decoder-only` parameter, the decoder will be initialized with the same XLM-R state dict.
> 
> Therefore, if you do not want to use the pre-trained models, do not pass `--init-encoder-only` or `--init-decoder-only` to the training script.
> 
> As for `--pretrained-infoxlm-checkpoint`, we can ignore this parameter, meaning we do not provide a valid model checkpoint, as mentioned in the [code](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/two_stage_sparse_transformer.py#L727).
> 
> > Furthermore, could you let me know which task you used for LS-MNMT? Perhaps it is language_specific_transformer?
> 
> **LS-MNMT**: [language_specific_transformer.py](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/language_specific_transformer.py)

Thank you for the details! I tried to reproduce the result, however, I got very different results (many of the language pairs have much worse results than MNMT baseline), could you please provide the detailed hyper-param setting for the 1. HLT-MT without pre-trained models; 2. LS-MNMT.

Because one potential reason could be some parameters need to be changed when applying HLT-MT without the pre-trained model such as: `--swap-adapter 0 --start-hard-epoch 1 --hard-adapter 0.5 --end-soft-epoch 5 --disparity-weight 1.0`.

**Comment by Smu-Tan** [comment]
> > I intended to reproduce the results without pre-trained models (third row in Table 3). If I understand correctly, I can just ignore `--pretrained-infoxlm-checkpoint`, and set `--init-encoder-only` `--init-decoder-only`?
> 
> Yes. As Line 571 and Line 577 in [two_stage_sparse_transformer](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/two_stage_sparse_transformer.py) show, the encoder will be initialized with the XLM-R state dict if we pass the `--init-encoder-only` parameter to the training script in README. Similarly, if we pass the `--init-decoder-only` parameter, the decoder will be initialized with the same XLM-R state dict.
> 
> Therefore, if you do not want to use the pre-trained models, do not pass `--init-encoder-only` or `--init-decoder-only` to the training script.
> 
> As for `--pretrained-infoxlm-checkpoint`, we can ignore this parameter, meaning we do not provide a valid model checkpoint, as mentioned in the [code](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/two_stage_sparse_transformer.py#L727).
> 
> > Furthermore, could you let me know which task you used for LS-MNMT? Perhaps it is language_specific_transformer?
> 
> **LS-MNMT**: [language_specific_transformer.py](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/language_specific_transformer.py)

BTW, I found `--init-encoder-only` is commented as `if set, don't load the InfoXLM weights and embeddings into decoder`, same as `--init-decoder-only`, so I guess this means if I run HLT-MT without pre-trained model, I should pass them?

Furthermore, I also tried to run without `--init-encoder-only` & `--init-decoder-only`, and got the following errors. Could you please double check it?

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "hlt-mt-env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "HLT-MT/fairseq/distributed_utils.py", line 333, in distributed_main
    main(cfg, **kwargs)
  File "HLT-MT/fairseq_cli/train.py", line 77, in main
    model = task.build_model(cfg.model)
  File "HLT-MT/fairseq/tasks/translation_multi_simple_epoch.py", line 216, in build_model
    return super().build_model(args)
  File "HLT-MT/fairseq/tasks/fairseq_task.py", line 566, in build_model
    model = models.build_model(args, self)
  File "HLT-MT/fairseq/models/__init__.py", line 93, in build_model
    return model.build_model(cfg, task)
  File "HLT-MT/fairseq/models/transformer_from_pretrained_infoxlm.py", line 67, in build_model
    return super().build_model(args, task)
  File "HLT-MT/fairseq/models/transformer.py", line 235, in build_model
    decoder = cls.build_decoder(args, tgt_dict, decoder_embed_tokens)
  File "HLT-MT/fairseq/models/two_stage_sparse_transformer.py", line 411, in build_decoder
    return TwoStageSparseDecoder(args, tgt_dict, embed_tokens)
  File "HLT-MT/fairseq/models/two_stage_sparse_transformer.py", line 707, in __init__
    assert hasattr(args, "high_langs") and hasattr(args, "low_langs"), "Please set high- and low-resource languages"
AssertionError: Please set high- and low-resource languages

**Comment by YuweiYin** [comment]
The full implementation of HLT-MT is certainly better than the baseline model, as we claimed in the paper about our method's effectiveness. This repository is all the code of HLT-MT implementation.

Unfortunately, reproducing exactly the same results requires strictly following all the experimental settings, including but not limited to data usage, method implementation, hyper-parameter setup, training settings (such as max epoch, batch size, and learning rate), results evaluation, etc.

In addition, the training process is always coupled with randomness, which helps bring better results but sometimes harms reproducibility, as commonly happens in the field.

---

As for the specific running errors, please debug on your own.
The implementation of HLT-MT is elaborated on in the paper and our code implementation. As for other experimental settings, we use other code versions described in their own paper and code implementation.

**Comment by Smu-Tan** [comment]
> The full implementation of HLT-MT is certainly better than the baseline model, as we claimed in the paper about our method's effectiveness. This repository is all the code of HLT-MT implementation.
> 
> Unfortunately, reproducing exactly the same results requires strictly following all the experimental settings, including but not limited to data usage, method implementation, hyper-parameter setup, training settings (such as max epoch, batch size, and learning rate), results evaluation, etc.

This is exactly what I mean by providing the specific hyper-parameter setting, since you have provided the a. data source; b. method implementation (codebase). Yet, hyper-parameters and training settings are not given. Consequently, this makes other researchers harder to reproduce the result. Besides, I'm not asking for the settings for a completely different experimental setup, instead, I'm asking for setups of Table 3 in the paper.

> As for the specific running errors, please debug on your own.

**I‘m not blaming the author because I cannot reproduce the same result, instead, I'm asking the author for guidance and help.** Furthermore, I found the response quite rude since it is your responsibility to provide a clear codebase and guidance for people to reproduce your experiment, otherwise, what is the point of uploading code?

**Comment by YuweiYin** [comment]
Sorry if you find the wording uncomfortable, we did try to help and guide you, as shown in previous answers.

This codebase is the full version of HLT-MT to show the core ideas of our method. For other settings/methods, we either slightly modify the current codebase or re-implement those methods according to their original papers. These counterparts are not provided here, and we are not maintaining and updating the code now. Although not the whole codebase of all experiments and methods, we believe releasing this final version has certain contributions.

> Yet, hyper-parameters and training settings are not given.

The hyper-parameters are provided in the training script in the README document ([HLT-MT Training](https://github.com/YuweiYin/HLT-MT#hlt-mt-training)).

> Furthermore, I also tried to run without `--init-encoder-only` & `--init-decoder-only`, and got the following errors. Could you please double-check it?

As for the presented running errors, whether we do or do not want to use the pre-trained model to initialize the encoder/decoder, there are only several lines to change in the [code](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/two_stage_sparse_transformer.py#L568). If you run the code line by line in the debugging mode, solving AttributeError such as "object has no attribute" should be easy. Specifically, check the Line 711 of [two_stage_sparse_transformer](https://github.com/YuweiYin/HLT-MT/blob/master/HLT-MT/fairseq/models/two_stage_sparse_transformer.py#L711) where `self.high_lang_tensor` is defined.
